### Register a new user
POST http://localhost:5002/api/auth/register
Content-Type: application/json

{
  "email": "testuser6@example.com",
  "password": "securePassword123@"
}


###Login with the registered user
POST http://localhost:5002/api/auth/login
Content-Type: application/json

{
  "email": "testuser6@example.com",
  "password": "securePassword123@"
}

###Start a new game(anonymous)
GET http://localhost:5002/api/gameRoutes/startGame
Content-Type: application/json

###Start a new game(authenticated)
GET http://localhost:5002/api/gameRoutes/startGame
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IkRhV3U5djcrN3FDT05zZGciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3FjbWFldG1xanJwdmJkd2Zqd3F4LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIwNTg2ZTUwNy0wZmFiLTQyN2EtYjI0NS0wZWNlNmQ3MzkzZTYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ5NTM3MzgzLCJpYXQiOjE3NDk1MzM3ODMsImVtYWlsIjoidGVzdHVzZXI2QGV4YW1wbGUuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InRlc3R1c2VyNkBleGFtcGxlLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInN1YiI6IjA1ODZlNTA3LTBmYWItNDI3YS1iMjQ1LTBlY2U2ZDczOTNlNiJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzQ5NTMzNzgzfV0sInNlc3Npb25faWQiOiJlODQyMGFhMC04OTU2LTRjYjQtOGFhMy02N2VjNDY5ZjRhZGUiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.5HGpkmUfqdueVf8AmOyxGTHxwdi-LAAQeMQpSHvNDFE

###
GET http://localhost:5002/api/gameRoutes/getPlayers
Content-Type: application/json

###
POST http://localhost:5002/api/gameRoutes/guess
Content-Type: application/json

{
  "playerName": "Gary Harris",
  "gameId": 401
}

###
GET http://localhost:5002/api/gameRoutes/getWins
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IkRhV3U5djcrN3FDT05zZGciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3FjbWFldG1xanJwdmJkd2Zqd3F4LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIwNTg2ZTUwNy0wZmFiLTQyN2EtYjI0NS0wZWNlNmQ3MzkzZTYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ5NTM3MzgzLCJpYXQiOjE3NDk1MzM3ODMsImVtYWlsIjoidGVzdHVzZXI2QGV4YW1wbGUuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InRlc3R1c2VyNkBleGFtcGxlLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInN1YiI6IjA1ODZlNTA3LTBmYWItNDI3YS1iMjQ1LTBlY2U2ZDczOTNlNiJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzQ5NTMzNzgzfV0sInNlc3Npb25faWQiOiJlODQyMGFhMC04OTU2LTRjYjQtOGFhMy02N2VjNDY5ZjRhZGUiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.5HGpkmUfqdueVf8AmOyxGTHxwdi-LAAQeMQpSHvNDFE


###
POST http://localhost:5002/api/gameRoutes/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IkRhV3U5djcrN3FDT05zZGciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3FjbWFldG1xanJwdmJkd2Zqd3F4LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIwNTg2ZTUwNy0wZmFiLTQyN2EtYjI0NS0wZWNlNmQ3MzkzZTYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ5NTM3MjA2LCJpYXQiOjE3NDk1MzM2MDYsImVtYWlsIjoidGVzdHVzZXI2QGV4YW1wbGUuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InRlc3R1c2VyNkBleGFtcGxlLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInN1YiI6IjA1ODZlNTA3LTBmYWItNDI3YS1iMjQ1LTBlY2U2ZDczOTNlNiJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzQ5NTMzNjA2fV0sInNlc3Npb25faWQiOiJkOGNlMDQ2YS1mZWNjLTRmZTYtOGU3ZS05OTEwNGM5OTNlMDMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.IP4S8f4-3VPB5s1Rf_dDeUmaclKJgP4m_Yq6M62QQjE

{}